# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trellis.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'trellis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtrellis.proto\"W\n\x11RadioUpdateHeader\x12\x0f\n\x07uint_id\x18\x01 \x01(\t\x12\x1e\n\x16\x65xpected_update_period\x18\x02 \x01(\r\x12\x11\n\trapid_pli\x18\x03 \x01(\x08\"L\n\x11\x45nvironmentStatus\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.RadioUpdateHeader\x12\x13\n\x0bnoise_floor\x18\x02 \x01(\x05\"C\n\x05Links\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.RadioUpdateHeader\x12\x16\n\x07payload\x18\x02 \x01(\x0b\x32\x05.Link\"\xf5\x01\n\x04Link\x12\x16\n\x0e\x64\x65stination_id\x18\x01 \x01(\t\x12\x1c\n\x14src_link_quality_snr\x18\x02 \x01(\x01\x12 \n\x18src_link_quality_percent\x18\x03 \x01(\r\x12\x1c\n\x14\x64st_link_quality_snr\x18\x04 \x01(\x01\x12 \n\x18\x64st_link_quality_percent\x18\x05 \x01(\r\x12\r\n\x05range\x18\x06 \x01(\x01\x12\x18\n\x10range_confidence\x18\x07 \x01(\r\x12\x15\n\rsrc_link_rssi\x18\x08 \x01(\r\x12\x15\n\rdst_link_rssi\x18\t \x01(\rb\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trellis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RADIOUPDATEHEADER']._serialized_start=17
  _globals['_RADIOUPDATEHEADER']._serialized_end=104
  _globals['_ENVIRONMENTSTATUS']._serialized_start=106
  _globals['_ENVIRONMENTSTATUS']._serialized_end=182
  _globals['_LINKS']._serialized_start=184
  _globals['_LINKS']._serialized_end=251
  _globals['_LINK']._serialized_start=254
  _globals['_LINK']._serialized_end=499
# @@protoc_insertion_point(module_scope)
